import '../globals.scss'
import { fontSans } from "@/utils/fonts"
import { cn } from "@/utils/utils"
import { ThemeContextProvider } from "@/context/theme-context"
import { adminConfig } from "@/config/site"

import Navbar from "@/components/blocks/header/navbar"
import Footer from "@/components/blocks/footer/footer"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}>
        <ThemeContextProvider>
          <div className="page-container">
            <Navbar siteInfo={{name: adminConfig.name, mainNav: adminConfig.frontendNav}} />
            <main className="main">{children}</main>
            <Footer />
          </div>   
        </ThemeContextProvider>        
      </body>
    </html>
  )
}
